DROP TABLE IF EXISTS TB_CSTM_CQRS;
DROP TABLE IF EXISTS TB_ACNT_CQRS;
DROP TABLE IF EXISTS TB_RCNT_WORK;


CREATE TABLE TB_CSTM_CQRS
(
  CSTM_ID    	VARCHAR(20) NOT NULL,
  CSTM_NM  	VARCHAR(100),
  CSTM_AGE 	VARCHAR(3),
  CSTM_GND 	VARCHAR(1),
  CSTM_PN   	VARCHAR(20),
  CSTM_ADR  	VARCHAR(1000),
  ONE_TM_TRNF_LMT	BIGINT DEFAULT 0,
  ONE_DY_TRNF_LMT	BIGINT DEFAULT 0	
)
;
COMMENT ON TABLE TB_CSTM_CQRS  
IS '고객CQRS';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_ID  
IS '고객번호';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_NM 
 IS '고객명';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_AGE  
IS '나이';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_GND  
IS '성별';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_PN 
IS '전화번호';
COMMENT ON COLUMN TB_CSTM_CQRS.CSTM_ADR  
IS '주소';
COMMENT ON COLUMN TB_CSTM_CQRS.ONE_TM_TRNF_LMT  
IS '1회이체한도';
COMMENT ON COLUMN TB_CSTM_CQRS.ONE_DY_TRNF_LMT  
IS '1일이체한도';
ALTER TABLE TB_CSTM_CQRS
  ADD CONSTRAINT TB_CSTM_CQRS_PK PRIMARY KEY (CSTM_ID);

CREATE TABLE TB_ACNT_CQRS
(
  ACNT_NO	VARCHAR(20) NOT NULL,
  CSTM_ID	VARCHAR(20),
  ACNT_NM	VARCHAR(20),
  NEW_DTM	VARCHAR(20),
  ACNT_BLNC	BIGINT DEFAULT 0
)
;
COMMENT ON TABLE TB_ACNT_CQRS
  IS '계좌CQRS';
COMMENT ON COLUMN TB_ACNT_CQRS.ACNT_NO
  IS '계좌번호';
COMMENT ON COLUMN TB_ACNT_CQRS.CSTM_ID
  IS '고객ID';
COMMENT ON COLUMN TB_ACNT_CQRS.ACNT_NM
  IS '계좌명';
COMMENT ON COLUMN TB_ACNT_CQRS.NEW_DTM
  IS '신규일시';
COMMENT ON COLUMN TB_ACNT_CQRS.ACNT_BLNC
  IS '계좌잔액';
ALTER TABLE TB_ACNT_CQRS
  ADD CONSTRAINT TB_ACNT_CQRS_PK PRIMARY KEY (ACNT_NO);
  
CREATE TABLE TB_RCNT_WORK
(
  CSTM_ID    	   VARCHAR(20) NOT NULL,
  CSTM_NM  	      VARCHAR(100),
  RCNT_WORK_DIV_CD 	VARCHAR(1),
  RCNT_WORK_DTM	   VARCHAR(20),
  WORK_ACNT_NO   	   VARCHAR(20),
  WORK_TRNS_AMT  	   BIGINT DEFAULT 0,
  WORK_STS_CD 	      VARCHAR(1)
)
;
COMMENT ON TABLE TB_RCNT_WORK
IS '최근작업';
COMMENT ON COLUMN TB_RCNT_WORK.CSTM_ID  
IS '고객번호';
COMMENT ON COLUMN TB_RCNT_WORK.CSTM_NM 
 IS '고객명';
COMMENT ON COLUMN TB_RCNT_WORK.RCNT_WORK_DIV_CD  
IS '최근작업구분코드';
COMMENT ON COLUMN TB_RCNT_WORK.RCNT_WORK_DTM  
IS '최근작업일시';
COMMENT ON COLUMN TB_RCNT_WORK.WORK_ACNT_NO
IS '작업계좌번호';
COMMENT ON COLUMN TB_RCNT_WORK.WORK_TRNS_AMT 
IS '작업거래금액';
COMMENT ON COLUMN TB_RCNT_WORK.WORK_STS_CD 
IS '작업상태코드';
ALTER TABLE TB_RCNT_WORK
  ADD CONSTRAINT TB_RCNT_WORK_PK PRIMARY KEY (CSTM_ID);