DROP TABLE IF EXISTS TB_ACNT;
DROP TABLE IF EXISTS TB_TRNS_HST;
DROP SEQUENCE IF EXISTS SEQ_ACCOUNT_TRANSACTION_HISTORY;

CREATE TABLE TB_ACNT
(
  ACNT_NO	VARCHAR(20) NOT NULL,
  CSTM_ID	VARCHAR(20) NOT NULL,
  CSTM_NM	VARCHAR(20) NOT NULL,
  ACNT_NM	VARCHAR(20) NOT NULL,
  NEW_DTM	VARCHAR(20) NOT NULL
)
;
COMMENT ON TABLE TB_ACNT
  IS '계좌';
COMMENT ON COLUMN TB_ACNT.ACNT_NO
  IS '계좌번호';
COMMENT ON COLUMN TB_ACNT.CSTM_ID
  IS '고객번호';
COMMENT ON COLUMN TB_ACNT.CSTM_NM
  IS '고객명';
COMMENT ON COLUMN TB_ACNT.ACNT_NM
  IS '계좌명';
COMMENT ON COLUMN TB_ACNT.NEW_DTM
  IS '신규일시';

ALTER TABLE TB_ACNT
  ADD CONSTRAINT TB_ACNT_PK PRIMARY KEY (ACNT_NO);

CREATE TABLE TB_TRNS_HST
(
  ACNT_NO	VARCHAR(20) NOT NULL,
  SEQ		INTEGER NOT NULL,
  DIV_CD		VARCHAR(1) NOT NULL,
  STS_CD  	VARCHAR(1) NOT NULL,
  TRNS_AMT	BIGINT DEFAULT 0,
  ACNT_BLNC	BIGINT DEFAULT 0,
  TRNS_BRNCH	VARCHAR(20) NOT NULL,
  TRNS_DTM	VARCHAR(20) NOT NULL
)
;
COMMENT ON TABLE TB_TRNS_HST
  IS '이체내역';
COMMENT ON COLUMN TB_TRNS_HST.ACNT_NO
  IS '계좌번호';
COMMENT ON COLUMN TB_TRNS_HST.SEQ
  IS '순번';
COMMENT ON COLUMN TB_TRNS_HST.DIV_CD
  IS '구분코드';
COMMENT ON COLUMN TB_TRNS_HST.STS_CD
  IS '상태코드';
COMMENT ON COLUMN TB_TRNS_HST.TRNS_AMT
  IS '거래금액';
COMMENT ON COLUMN TB_TRNS_HST.ACNT_BLNC
  IS '계좌잔액';
COMMENT ON COLUMN TB_TRNS_HST.TRNS_BRNCH
  IS '거래점';
COMMENT ON COLUMN TB_TRNS_HST.TRNS_DTM
  IS '거래일시';
ALTER TABLE TB_TRNS_HST
  ADD CONSTRAINT TB_TRNS_HST_PK PRIMARY KEY (ACNT_NO,SEQ);

CREATE SEQUENCE SEQ_ACCOUNT_TRANSACTION_HISTORY;